name: Run Tests

on:
  push:
    branches:
      - changes # or 'master', or any branch you want
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or whatever version you use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # or `npm run test` or `yarn test` depending on your setup
